name: moespa
favicon: null
layout_spectrum: 0.28142770333215594
typography_spectrum: 0.14588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e2a2d'
    - '#d0d0ce'
    - '#939c9b'
    - '#fcfcfc'
    - '#5d7a7e'
  brandStrength: 0.9375
  lightness: 0.9029738171957433
  saturation: 0.2181593757122755
  rhythmicContrast: 0.596396082546562
purpose: []
